In [1]:
# é comum abreviar a biblioteca numpy como np 
import numpy as np
import math



In [2]:
#arrays são exibidos com uma lista ou lista de listas 
#vamos criar uma array, passando uma lista de argumentos para ele
a = np.array([1, 2, 3])
print(a)
# podemos imprimir a dimensão dessa lista usando ndim atributo
print(a.ndim)

[1 2 3]
1


In [4]:
#se criarmos uma lista contendo listas com numpy.array teremos um array multi - dimensional
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#nos podemos imprimir a dimensão desse array com o atributo .shape
b.shape

(2, 3)

In [7]:
#podemos verificar o tipo de items no array
a.dtype

dtype('int64')

In [8]:
# se usarmos float 
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [9]:
c

array([2.2, 5. , 1.1])

In [10]:
#note que o numpy transformou o 5 em numero flutuante para tornar nosso tipo de dados homogeneo
#vamos criar 2 array do mesmo tamanho mas com valores diferentes

d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#vamos gerar tbm um array com numeros randomicos
np.random.rand(2,3)

array([[0.27925212, 0.25745727, 0.89727755],
       [0.82879251, 0.54344565, 0.14234487]])

In [15]:
#podemos usar o np.arange para criar uma sequencia de numeros o primeiro argumento e o começo 
# e o segundo argumento e o final, já o terceiro arumento e o intervalo que este numero vai seguir
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [16]:
#podemos gerar um sequencia com numeros flutuantes usando linspace()
#o terceiro arumento e a quantidade de numeros que queremos gerar 

np.linspace( 0, 2, 15 ) # 15 numeros entre 0 e 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Operações com Array
